apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: catalog-service
  name: catalog-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: catalog-service
    spec:
      containers:
      - args:
        - node
        - src/index.js
        image: jackhammond/fyp:catalog-service
        name: catalog-service
        ports:
        - containerPort: 4000
        resources: {}
      restartPolicy: Always
      - args:
        - mongod
        - --logpath=/dev/null
        env:
        - name: MONGO_DATA_DIR
          value: /data/db
        - name: MONGO_LOG_DIR
          value: /dev/null
        image: mongo
        name: mongo-catalog
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: mongo-catalog-claim0
      restartPolicy: Always
      volumes:
      - name: mongo-catalog-claim0
        persistentVolumeClaim:
          claimName: mongo-catalog-claim0
status: {}
