#!/bin/bash

						#nodejs backend setup

#OAUTH_TOKEN='ff452dfb5f8c421641791e7f40e576920845d8b1'

#sudo apt update

#sudo apt install git

#sudo git clone https://$OAUTH_TOKEN:x-oauth-basic@github.com/JackHammond/FYP.git

sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -

sudo apt install nodejs

sudo apt install -y mongodb

cd FYP/Monolithic/mono_flutter_back_end/ 

npm install

npm install forever -g

npm install forever-monitor

forever start src/index.js


						#flutter nginx setup

cd ~

cd FYP/Monolithic/mono_fluter_front_end

sudo apt-get clean

sudo apt-get install -y curl git wget unzip libgconf-2-4 gdb libstdc++6 libglu1-mesa fonts-droid-fallback lib32stdc++6 python3

sudo apt-get clean

sudo git clone https://github.com/flutter/flutter.git /usr/local/flutter

sudo /usr/local/flutter/bin/flutter doctor -v

PATH="$PATH:/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin"

sudo chown -R $USER:$USER /usr/local/flutter/ 

flutter channel master

flutter upgrade

flutter config --enable-web

/usr/local/flutter/bin/flutter build web

sudo apt install nginx

sudo cp -r build/web/* /var/www/html/

sudo systemctl start nginx
