version: '2.1'
services:
    basket:
        build: .
        container_name: basket-service
        image: basket-service
        restart: always
        command: node src/index.js
        ports:
            - "4002:4002"
        depends_on:
            - mongodb
    mongodb:
        image: mongo
        container_name: mongo_basket
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
           - ./data:/data/db
        ports:
            - "27017:27017"
        command: mongod start
        command: mongod --logpath=/dev/null # --quiet

