IMAGE_NAME = "centos/7"
N = 2

 Vagrant.configure("2") do |config|
    #config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end 

    config.vm.define "master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.30.10"
        master.vm.hostname = "master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes-setup/kube-dependencies.yml"
            ansible.extra_vars = {
                node_ip: "192.168.30.10",
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "worker-#{i}" do |worker|
            worker.vm.box = IMAGE_NAME
            worker.vm.network "private_network", ip: "192.168.30.#{i+10}"
            worker.vm.hostname = "worker-#{i}"
            worker.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes-setup/worker-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.30.#{i+10}",
                }
            end
        end
    end
end
