apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-review
  name: mongo-review
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-review
    spec:
      containers:
      - args:
        - mongod
        - --logpath=/dev/null
        env:
        - name: MONGO_DATA_DIR
          value: /data/db
        - name: MONGO_LOG_DIR
          value: /dev/null
        image: mongo
        name: mongo-review
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: mongo-review-claim0
      restartPolicy: Always
      volumes:
      - name: mongo-review-claim0
        persistentVolumeClaim:
          claimName: mongo-review-claim0
status: {}
