version: '2'
services:
    catalog-service:
        build: .
        container_name: catalog-service
        image: jackhammond/fyp:catalog-service
        #restart: always
        command: node src/index.js
        ports:
            - "4000:4000"
        depends_on:
            - mongo-catalog
            - eureka-service
            - zuul-service
    mongo-catalog:
        image: mongo
        container_name: mongo_catalog
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
           - ./data:/data
        ports:
            - "27017:27017"
        command: mongod start
        command: mongod --logpath=/dev/null # --quiet
    review-service:
        build: ../Review/
        container_name: review-service
        image: jackhammond/fyp:review-service
        #restart: always
        command: node src/index.js
        ports:
            - "4001:4001"
        depends_on:
            - mongo-review
            - eureka-service
            - zuul-service
    mongo-review:
        image: mongo
        container_name: mongo_review
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
           - ./data:/data
        ports:
            - "27018:27017"
        #command: mongod start
        command: mongod start
        command: mongod --logpath=/dev/null # --quiet
    basket-service:
        build: ../Basket/
        container_name: basket-service
        image: jackhammond/fyp:basket-service
        #restart: always
        command: node src/index.js
        ports:
            - "4002:4002"
        depends_on:
            - mongo-basket
            - eureka-service
            - zuul-service
    mongo-basket:
        image: mongo
        container_name: mongo_basket
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
           - ./data:/data
        ports:
            - "27019:27017"
        #command: mongod start
        command: mongod start
        command: mongod --logpath=/dev/null # --quiet
    flutter-front-end:
        build: ../../ms_flutter_front_end/
        image: jackhammond/fyp:flutter-front-end
        container_name: flutter-front-end
        ports:
           - "8080:80"
        depends_on:
           - zuul-service
           - eureka-service
    eureka-service:
        image: jackhammond/fyp:eureka-service
        container_name: eureka-service
        build: ../r-d-service/r-d-service/
        ports:
          - 8761:8761
    zuul-service:
        image: jackhammond/fyp:zuul-service
        container_name: zuul-service
        build: ../zuul.service/zuul.service/
        ports:
          - 8762:8762

